// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAEW296tfCJ0X_DOHSMt2ZZvm8xSXkPtM',
    appId: '1:598500886920:web:997d44229fb8bcbcaa523d',
    messagingSenderId: '598500886920',
    projectId: 'fir-auth-bd49b',
    authDomain: 'fir-auth-bd49b.firebaseapp.com',
    databaseURL: 'https://fir-auth-bd49b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-bd49b.appspot.com',
    measurementId: 'G-YWXBM1CXT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54vPBNAJiKB27iK6P0Vp2u6veT5ALdSM',
    appId: '1:598500886920:android:4ce05e720ae80b29aa523d',
    messagingSenderId: '598500886920',
    projectId: 'fir-auth-bd49b',
    databaseURL: 'https://fir-auth-bd49b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-bd49b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2C5s0DEDB0a9NE4o8Ipi1VRqXjwb--Wc',
    appId: '1:598500886920:ios:6cf06d6eb3c39b1eaa523d',
    messagingSenderId: '598500886920',
    projectId: 'fir-auth-bd49b',
    databaseURL: 'https://fir-auth-bd49b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-bd49b.appspot.com',
    iosClientId: '598500886920-7qp66d3nljb0evflap561sv4b4glkef6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinjamBuku2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2C5s0DEDB0a9NE4o8Ipi1VRqXjwb--Wc',
    appId: '1:598500886920:ios:6cf06d6eb3c39b1eaa523d',
    messagingSenderId: '598500886920',
    projectId: 'fir-auth-bd49b',
    databaseURL: 'https://fir-auth-bd49b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-bd49b.appspot.com',
    iosClientId: '598500886920-7qp66d3nljb0evflap561sv4b4glkef6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinjamBuku2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAEW296tfCJ0X_DOHSMt2ZZvm8xSXkPtM',
    appId: '1:598500886920:web:84b02a76aaeebb53aa523d',
    messagingSenderId: '598500886920',
    projectId: 'fir-auth-bd49b',
    authDomain: 'fir-auth-bd49b.firebaseapp.com',
    databaseURL: 'https://fir-auth-bd49b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-bd49b.appspot.com',
    measurementId: 'G-MPMTKYKCQR',
  );
}
